### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by haobarry** [remix-project-org/remix-desktop-insiders#9]
Opening a blank page, the proxy is also on but it's not working.

**Comment by bunsenstraat** [comment]
which proxy are you referring too? can you share some info about your OS?

**Comment by haobarry** [comment]
I am using Windows 11 Professional Edition, and I have already turned on the proxy, but it is still a white screen.
![image](https://github.com/user-attachments/assets/acb0193b-a036-4ed3-8792-790d55d9742e)

**Comment by haobarry** [comment]
i found problem there's a '#' symbol in the middle of my folder's name. 😥
